// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=mock_gen_interface.go -package=task
//

// Package task is a generated GoMock package.
package task

import (
	task "microservice/Models/task"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// Mockstore is a mock of Store interface.
type Mockstore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for Mockstore.
type MockStoreMockRecorder struct {
	mock *Mockstore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *Mockstore {
	mock := &Mockstore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockstore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// Completetask mocks base method.
func (m *Mockstore) Completetask(id int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Completetask", id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Completetask indicates an expected call of Completetask.
func (mr *MockStoreMockRecorder) Completetask(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Completetask", reflect.TypeOf((*Mockstore)(nil).Completetask), id)
}

// Deletetask mocks base method.
func (m *Mockstore) Deletetask(id int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deletetask", id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Deletetask indicates an expected call of Deletetask.
func (mr *MockStoreMockRecorder) Deletetask(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deletetask", reflect.TypeOf((*Mockstore)(nil).Deletetask), id)
}

// Getalltask mocks base method.
func (m *Mockstore) Getalltask() ([]task.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Getalltask")
	ret0, _ := ret[0].([]task.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Getalltask indicates an expected call of Getalltask.
func (mr *MockStoreMockRecorder) Getalltask() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Getalltask", reflect.TypeOf((*Mockstore)(nil).Getalltask))
}

// Gettaskbyid mocks base method.
func (m *Mockstore) Gettaskbyid(id int) (*task.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Gettaskbyid", id)
	ret0, _ := ret[0].(*task.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Gettaskbyid indicates an expected call of Gettaskbyid.
func (mr *MockStoreMockRecorder) Gettaskbyid(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Gettaskbyid", reflect.TypeOf((*Mockstore)(nil).Gettaskbyid), id)
}

// Insertask mocks base method.
func (m *Mockstore) Insertask(t task.Task) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insertask", t)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insertask indicates an expected call of Insertask.
func (mr *MockStoreMockRecorder) Insertask(t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insertask", reflect.TypeOf((*Mockstore)(nil).Insertask), t)
}
