basePath: /
host: localhost:8080
info:
  contact: {}
  description: This is a microservice for managing tasks and users.
  title: Task & User Microservice API
  version: "1.0"
paths: {}
swagger: "2.0"
